### ISSUE TITLE
Possible to add logo in site title?

### ISSUE THREAD

**Issue by amarc** [ojroques/hugo-researcher#12]
Hello, as per above, would it be possible to add small logo in site name either logo only or text+logo ? 

ty.

**Comment by ojroques** [comment]
Hello!

I've added support for a header logo. Use the new option like so: https://github.com/ojroques/hugo-researcher/blob/b0edab5611fceeef86d5c592ca51530bf3286ec6/exampleSite/config.toml#L13

It's up to you to format the image so that it fits the header. To use only the logo simply set the `title` option to an empty string.
