### ISSUE TITLE
sitemap absent

### ISSUE THREAD

**Issue by somnathrakshit** [ojroques/hugo-researcher#6]
Is it possible to automatically generate the sitemap.xml file? It will be useful since all major search engines rely on sitemap file for indexing.

**Comment by ojroques** [comment]
Hello,
The sitemap is automatically generated by Hugo when you're building your website: see [here](https://gohugo.io/templates/sitemap-template/). It should be accessible at https://your-site.dev/sitemap.xml. Hope that helps.

**Comment by somnathrakshit** [comment]
I tried generating my own website and that doesn't work. I also tried the demo site, which doesn't seem to work as well.
demo site: https://themes.gohugo.io/theme/hugo-researcher/sitemap.xml
my site: https://somnathrakshit.github.io/sitemap.xml

**Comment by ojroques** [comment]
Mmh that's weird, I'm also using the theme for my website and the sitemap is there: https://oroques.dev/sitemap.xml.
Try updating the theme to latest commit, I've recently made change to links due to #5 maybe that's the issue. Note that if you had a link to a static content such as `[img](picture.png)` now it should be changed to  `[img](/picture.png)`.

**Comment by somnathrakshit** [comment]
I think I understand what's happening. Just removed sitemap from this line in config.toml and it's working now.
`disableKinds = ["taxonomy", "term", "robotsTXT"]`

**Comment by ojroques** [comment]
Good to know! I've updated the example website with your fix.
