### ISSUE TITLE
Possible to use different font?

### ISSUE THREAD

**Issue by somnathrakshit** [ojroques/hugo-researcher#7]
Is there an easy way to use a different font for the website?

**Comment by ojroques** [comment]
Unfortunately no, to change the font you need to modify the theme itself. I don't plan to add the option of changing fonts because Inconsolata is at the core of this theme's design and I'm not even sure it is programmatically possible with Hugo themes, sorry.

But you're welcome to directly edit the code or fork this theme. Here are the lines you need to change:
https://github.com/ojroques/hugo-researcher/blob/51fc9574a00b9399a8734a9849e8c2796ea05e75/layouts/partials/head.html#L9
https://github.com/ojroques/hugo-researcher/blob/51fc9574a00b9399a8734a9849e8c2796ea05e75/assets/sass/researcher.scss#L39

**Comment by ojroques** [comment]
I've just pushed support for font customization: you can now select the font to use in your website config. 

The font you choose must be present at the visitor side. Therefore you must either:
* Choose a font that is very common such as *Arial* etc. Or select *Inconsolata* which is installed by default by the theme.
* Or modify [this line](https://github.com/ojroques/hugo-researcher/blob/5dc15490ccc07d5e45f51a7a0a0560bd0155301f/layouts/partials/head.html#L9) to download the font you want.
* Or self-host the font and add a link to it in the sass file [here](https://github.com/ojroques/hugo-researcher/blob/5dc15490ccc07d5e45f51a7a0a0560bd0155301f/assets/sass/researcher.scss#L46-L50). See [CSS Web Fonts](https://www.w3schools.com/css/css3_fonts.asp) (section *Using The Font You Want*) for how to do that.
